### ISSUE TITLE
[KIT-2] - Centralizar Dangerfile

### ISSUE THREAD

**Issue by Vitor-Gouveia** [Vitor-Gouveia/dev-kit#3]
Diminuir a complexidade dos serviços Minu centralizando a configuração do dangerfile na biblioteca `@vitorgouveia/dev-kit`

---

# Discovery

Existem 2 formas de fazer isso funcionar.

1. Esconder toda a configuração na biblioteca e fazer um import no `dangerfile.js`

```js
const { dangerfile } = require("@vitorgouveia/dev-kit")

dangerfile()
```

> O problema dessa abordagem é ter que ficar atualizando versão do pacote. Mas deve ser levado em consideração também que o dangerfile não é sujeito a muitas alterações.

2. Executar isso de alguma forma no github actions

No arquivo do github actions do danger é possível executar um script do dev-kit para criar um dangerfile e rodar ele.

Sendo apenas necessário o "danger" instalado no serviço. (Que é ruim)

```yml
name: "Danger JS"
on: [pull_request]
jobs:
  danger:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20.11.0

      - name: Setup GitHub Packages Token
        run: |
          echo '@minutrade:registry=https://npm.pkg.github.com/' >> .npmrc
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.GH_PIPELINE_TOKEN }}' >> .npmrc

      - name: Running Danger on CI
        env:
          DANGER_GITHUB_API_TOKEN:  ${{ secrets.GH_PIPELINE_TOKEN }}
        run: |
          npx @vitorgouveia/dev-kit dangerfile
          npm i danger
          npx danger ci --failOnErrors
```
